USE [master]
GO
/****** Object:  Database [FOOTDRAFT]    Script Date: 06/03/2025 15:06:23 ******/
CREATE DATABASE [FOOTDRAFT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FOOTDRAFT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FOOTDRAFT.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FOOTDRAFT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FOOTDRAFT_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FOOTDRAFT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FOOTDRAFT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FOOTDRAFT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET ARITHABORT OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FOOTDRAFT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FOOTDRAFT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FOOTDRAFT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FOOTDRAFT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FOOTDRAFT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FOOTDRAFT] SET  MULTI_USER 
GO
ALTER DATABASE [FOOTDRAFT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FOOTDRAFT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FOOTDRAFT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FOOTDRAFT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FOOTDRAFT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FOOTDRAFT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FOOTDRAFT] SET QUERY_STORE = ON
GO
ALTER DATABASE [FOOTDRAFT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FOOTDRAFT]
GO
/****** Object:  User [footdraft_user]    Script Date: 06/03/2025 15:06:23 ******/
CREATE USER [footdraft_user] FOR LOGIN [footdraft_user] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Bets]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bets](
	[BetUUID] [uniqueidentifier] NOT NULL,
	[UserUUID] [uniqueidentifier] NOT NULL,
	[MatchUUID] [uniqueidentifier] NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[PredictedWinner] [varchar](50) NOT NULL,
	[Status] [varchar](20) NOT NULL,
	[HomeTeamUUID] [uniqueidentifier] NOT NULL,
	[AwayTeamUUID] [uniqueidentifier] NOT NULL,
	[Winnings] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Bets] PRIMARY KEY CLUSTERED 
(
	[BetUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Matches]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Matches](
	[MatchUUID] [uniqueidentifier] NOT NULL,
	[TournamentUUID] [uniqueidentifier] NOT NULL,
	[HomeTeamUUID] [uniqueidentifier] NOT NULL,
	[AwayTeamUUID] [uniqueidentifier] NOT NULL,
	[HomeGoals] [int] NOT NULL,
	[AwayGoals] [int] NOT NULL,
	[MatchDate] [datetime] NOT NULL,
	[CurrentMinute] [int] NOT NULL,
 CONSTRAINT [PK_Matches] PRIMARY KEY CLUSTERED 
(
	[MatchUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MatchEvents]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MatchEvents](
	[EventUUID] [uniqueidentifier] NOT NULL,
	[MatchUUID] [uniqueidentifier] NOT NULL,
	[PlayerUUID] [uniqueidentifier] NOT NULL,
	[EventType] [varchar](50) NOT NULL,
	[Minute] [int] NOT NULL,
	[Description] [varchar](255) NOT NULL,
 CONSTRAINT [PK_MatchEvents] PRIMARY KEY CLUSTERED 
(
	[EventUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Players]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Players](
	[PlayerUUID] [uniqueidentifier] NOT NULL,
	[PlayerName] [varchar](50) NOT NULL,
	[Position] [varchar](20) NOT NULL,
	[Points] [int] NOT NULL,
	[TeamUUID] [uniqueidentifier] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Price] [decimal](15, 2) NOT NULL,
	[Height] [int] NULL,
	[Speed] [int] NULL,
	[Shooting] [int] NULL,
	[IsForSale] [bit] NOT NULL,
	[ReserveUserUUID] [uniqueidentifier] NULL,
	[PlayerImage] [varchar](max) NULL,
 CONSTRAINT [PK_Players] PRIMARY KEY CLUSTERED 
(
	[PlayerUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PlayerStatistics]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlayerStatistics](
	[PlayerUUID] [uniqueidentifier] NOT NULL,
	[Goals] [int] NOT NULL,
	[Assists] [int] NOT NULL,
	[YellowCards] [int] NOT NULL,
	[RedCards] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PlayerUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teams]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teams](
	[TeamUUID] [uniqueidentifier] NOT NULL,
	[TeamName] [varchar](50) NOT NULL,
	[TeamLogo] [varbinary](max) NULL,
	[ShirtColor] [varchar](20) NOT NULL,
	[UserUUID] [uniqueidentifier] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CoachName] [varchar](50) NULL,
 CONSTRAINT [PK_Teams] PRIMARY KEY CLUSTERED 
(
	[TeamUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Teams_TeamName] UNIQUE NONCLUSTERED 
(
	[TeamName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teams_Tournaments]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teams_Tournaments](
	[TeamUUID] [uniqueidentifier] NOT NULL,
	[TournamentUUID] [uniqueidentifier] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TeamUUID] ASC,
	[TournamentUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tournaments]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tournaments](
	[TournamentUUID] [uniqueidentifier] NOT NULL,
	[TournamentName] [varchar](100) NOT NULL,
	[TournamentType] [varchar](20) NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NULL,
 CONSTRAINT [PK_Tournaments] PRIMARY KEY CLUSTERED 
(
	[TournamentUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 06/03/2025 15:06:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserUUID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[PasswordHash] [varchar](255) NOT NULL,
	[RegistrationDate] [datetime] NOT NULL,
	[Footcoins] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Users_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bets] ADD  DEFAULT (newid()) FOR [BetUUID]
GO
ALTER TABLE [dbo].[Bets] ADD  DEFAULT ('pending') FOR [Status]
GO
ALTER TABLE [dbo].[Matches] ADD  DEFAULT (newid()) FOR [MatchUUID]
GO
ALTER TABLE [dbo].[Matches] ADD  DEFAULT ((0)) FOR [HomeGoals]
GO
ALTER TABLE [dbo].[Matches] ADD  DEFAULT ((0)) FOR [AwayGoals]
GO
ALTER TABLE [dbo].[Matches] ADD  DEFAULT ((0)) FOR [CurrentMinute]
GO
ALTER TABLE [dbo].[MatchEvents] ADD  DEFAULT (newid()) FOR [EventUUID]
GO
ALTER TABLE [dbo].[Players] ADD  DEFAULT (newid()) FOR [PlayerUUID]
GO
ALTER TABLE [dbo].[Players] ADD  DEFAULT ((0)) FOR [Points]
GO
ALTER TABLE [dbo].[Players] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Players] ADD  DEFAULT ((0)) FOR [Price]
GO
ALTER TABLE [dbo].[Players] ADD  DEFAULT ((1)) FOR [IsForSale]
GO
ALTER TABLE [dbo].[PlayerStatistics] ADD  DEFAULT ((0)) FOR [Goals]
GO
ALTER TABLE [dbo].[PlayerStatistics] ADD  DEFAULT ((0)) FOR [Assists]
GO
ALTER TABLE [dbo].[PlayerStatistics] ADD  DEFAULT ((0)) FOR [YellowCards]
GO
ALTER TABLE [dbo].[PlayerStatistics] ADD  DEFAULT ((0)) FOR [RedCards]
GO
ALTER TABLE [dbo].[Teams] ADD  DEFAULT (newid()) FOR [TeamUUID]
GO
ALTER TABLE [dbo].[Teams] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Tournaments] ADD  DEFAULT (newid()) FOR [TournamentUUID]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (newid()) FOR [UserUUID]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [RegistrationDate]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((100000)) FOR [Footcoins]
GO
ALTER TABLE [dbo].[Bets]  WITH CHECK ADD  CONSTRAINT [FK_Bets_AwayTeam] FOREIGN KEY([AwayTeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
GO
ALTER TABLE [dbo].[Bets] CHECK CONSTRAINT [FK_Bets_AwayTeam]
GO
ALTER TABLE [dbo].[Bets]  WITH CHECK ADD  CONSTRAINT [FK_Bets_HomeTeam] FOREIGN KEY([HomeTeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
GO
ALTER TABLE [dbo].[Bets] CHECK CONSTRAINT [FK_Bets_HomeTeam]
GO
ALTER TABLE [dbo].[Bets]  WITH CHECK ADD  CONSTRAINT [FK_Bets_Matches] FOREIGN KEY([MatchUUID])
REFERENCES [dbo].[Matches] ([MatchUUID])
GO
ALTER TABLE [dbo].[Bets] CHECK CONSTRAINT [FK_Bets_Matches]
GO
ALTER TABLE [dbo].[Bets]  WITH CHECK ADD  CONSTRAINT [FK_Bets_Users] FOREIGN KEY([UserUUID])
REFERENCES [dbo].[Users] ([UserUUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Bets] CHECK CONSTRAINT [FK_Bets_Users]
GO
ALTER TABLE [dbo].[Matches]  WITH CHECK ADD  CONSTRAINT [FK_Matches_AwayTeam] FOREIGN KEY([AwayTeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
GO
ALTER TABLE [dbo].[Matches] CHECK CONSTRAINT [FK_Matches_AwayTeam]
GO
ALTER TABLE [dbo].[Matches]  WITH CHECK ADD  CONSTRAINT [FK_Matches_HomeTeam] FOREIGN KEY([HomeTeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
GO
ALTER TABLE [dbo].[Matches] CHECK CONSTRAINT [FK_Matches_HomeTeam]
GO
ALTER TABLE [dbo].[Matches]  WITH CHECK ADD  CONSTRAINT [FK_Matches_Tournaments] FOREIGN KEY([TournamentUUID])
REFERENCES [dbo].[Tournaments] ([TournamentUUID])
GO
ALTER TABLE [dbo].[Matches] CHECK CONSTRAINT [FK_Matches_Tournaments]
GO
ALTER TABLE [dbo].[MatchEvents]  WITH CHECK ADD  CONSTRAINT [FK_MatchEvents_Matches] FOREIGN KEY([MatchUUID])
REFERENCES [dbo].[Matches] ([MatchUUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MatchEvents] CHECK CONSTRAINT [FK_MatchEvents_Matches]
GO
ALTER TABLE [dbo].[MatchEvents]  WITH CHECK ADD  CONSTRAINT [FK_MatchEvents_Players] FOREIGN KEY([PlayerUUID])
REFERENCES [dbo].[Players] ([PlayerUUID])
GO
ALTER TABLE [dbo].[MatchEvents] CHECK CONSTRAINT [FK_MatchEvents_Players]
GO
ALTER TABLE [dbo].[Players]  WITH CHECK ADD  CONSTRAINT [FK_Players_Teams] FOREIGN KEY([TeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Players] CHECK CONSTRAINT [FK_Players_Teams]
GO
ALTER TABLE [dbo].[Players]  WITH CHECK ADD  CONSTRAINT [FK_Players_Users] FOREIGN KEY([ReserveUserUUID])
REFERENCES [dbo].[Users] ([UserUUID])
GO
ALTER TABLE [dbo].[Players] CHECK CONSTRAINT [FK_Players_Users]
GO
ALTER TABLE [dbo].[PlayerStatistics]  WITH CHECK ADD FOREIGN KEY([PlayerUUID])
REFERENCES [dbo].[Players] ([PlayerUUID])
GO
ALTER TABLE [dbo].[Teams]  WITH CHECK ADD  CONSTRAINT [FK_Teams_Users] FOREIGN KEY([UserUUID])
REFERENCES [dbo].[Users] ([UserUUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Teams] CHECK CONSTRAINT [FK_Teams_Users]
GO
ALTER TABLE [dbo].[Teams_Tournaments]  WITH CHECK ADD FOREIGN KEY([TeamUUID])
REFERENCES [dbo].[Teams] ([TeamUUID])
GO
ALTER TABLE [dbo].[Teams_Tournaments]  WITH CHECK ADD FOREIGN KEY([TournamentUUID])
REFERENCES [dbo].[Tournaments] ([TournamentUUID])
GO
ALTER TABLE [dbo].[Players]  WITH CHECK ADD CHECK  (([Position]='Goalkeeper' OR [Position]='Defender' OR [Position]='Midfielder' OR [Position]='Forward'))
GO
ALTER TABLE [dbo].[Tournaments]  WITH CHECK ADD CHECK  (([TournamentType]='Knockout' OR [TournamentType]='League' OR [TournamentType]='Mixed'))
GO
USE [master]
GO
ALTER DATABASE [FOOTDRAFT] SET  READ_WRITE 
GO
